name: make term

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/term.yml
      - temrs.md
      - scripts/make-term.ts
      - scripts/style/term.scss
  workflow_dispatch:

jobs:
  renew-term:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .node-version
      - run: corepack enable pnpm
      - name: Get current time
        uses: josStorer/get-current-time@v2.1.1
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: '+09:00'
      - name: install
        run: pnpm install
      - name: make pdf
        run: pnpm run make-term

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: engine_rules_${{ steps.current-time.outputs.formattedTime }}.html
          path: ./term.html

      - uses: actions/upload-artifact@v4.3.1
        with:
          name: engine_rules_${{ steps.current-time.outputs.formattedTime }}.pdf
          path: ./term.pdf
