name: make term

on:
  push:
    branches:
      - main
    paths:
      - temrs.md
      - scripts/make-term.ts
      - scripts/style/term.scss
      - .github/workflows/term.yml
  workflow_dispatch:

jobs:
  renew-term:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: '+09:00'
      - name: install
        run: yarn
      - name: make pdf
        run: yarn make-term

      - uses: actions/upload-artifact@v2
        with:
          name: engine_rules_${{ steps.current-time.outputs.formattedTime }}.html
          path: ./term.html

      - uses: actions/upload-artifact@v2
        with:
          name: engine_rules_${{ steps.current-time.outputs.formattedTime }}.pdf
          path: ./term.pdf
